const express  = require('express');
const router   = express.Router();
const { autenticar, autorizar } = require('../middleware/auth');
const authCtrl      = require('../controllers/authController');
const agendCtrl     = require('../controllers/agendamentosController');
const negociosCtrl  = require('../controllers/negociosController');
const servicosCtrl  = require('../controllers/servicosController');
router.post('/auth/registrar', authCtrl.registrar);
router.post('/auth/login',     authCtrl.login);
router.get('/negocios',     negociosCtrl.listar);
router.get('/negocios/:id', negociosCtrl.detalhe);
router.post('/negocios',         autenticar, autorizar('dono', 'admin'), negociosCtrl.criar);
router.put('/negocios/:id',      autenticar, autorizar('dono', 'admin'), negociosCtrl.atualizar);
router.get('/negocios/:negocio_id/servicos',      servicosCtrl.listar);
router.post('/negocios/:negocio_id/servicos',     autenticar, autorizar('dono', 'admin'), servicosCtrl.criar);
router.delete('/negocios/:negocio_id/servicos/:id', autenticar, autorizar('dono', 'admin'), servicosCtrl.remover);
router.get('/agendamentos',          autenticar, agendCtrl.listar);
router.post('/agendamentos',         autenticar, autorizar('cliente'), agendCtrl.criar);
router.patch('/agendamentos/:id/cancelar', autenticar, agendCtrl.cancelar);
router.patch('/agendamentos/:id/status',  autenticar, autorizar('dono', 'admin'), agendCtrl.atualizarStatus);
module.exports = router;